### PR TITLE
Remove quartz dependency

### LINKED ISSUE #11: Remove quartz dependency
It seems unnecessary with some minor refactoring.

### PR DESCRIPTION
**Pull request by varunu28**
Pull Request type
----
- [ ] Bugfix
- [ ] Feature
- [X] Refactoring (no functional changes, no api changes)
- [X] Build related changes (Please run `./gradlew build --write-locks` to refresh dependencies)
- [ ] Other (please describe):

**NOTE**: Please remember to run `./gradlew spotlessApply` to fix any format violations.

Changes in this PR
----
This fixes #11 to remove the `quartz` dependency
 - Remove dependency on `quartz`
 - Refactor cron creation flow to use `Cron` instead of `CronExpression`
 - Impact of this change is that cron creation with a timezone is not possible but the execution time for the cron can be calculated using `nextExecutionTime` by providing a timezone.

### CODE REVIEW

**Comment by varunu28** [comment]
@jun-he Please do a round of review whenever you get a chance? I am open to feedback on how can we support cron creation along with timezone during the creation operation.

**Comment by jun-he** [comment]
@varunu28  thanks for the contribution. Will review it soon.

**Comment by jun-he** [comment]
@varunu28  can you rebase your change?

**Comment by varunu28** [comment]
> @varunu28 can you rebase your change?

Done

**Comment by varunu28** [comment]
@jun-he Bump on this for review. Thanks 👍

**Comment by jun-he** [comment]
@varunu28 Will review it soon.

**Pull request closed without merging**
